export enum TypeBusiness {
  ADMINISTRACION = 'ADMINISTRACION',
  SERVICIO = 'SERVICIO',
  TIENDA = 'TIENDA',
  RESTAURANT = 'RESTAURANT',
  HOTEL = 'HOTEL',
  CAPACITACION = 'CAPACITACION',
  INSTITUTO = 'INSTITUTO',
  COLEGIO = 'COLEGIO',
  TRANSPORTE = 'TRANSPORTE',
}
